# Generated by Django 5.2.1 on 2025-05-10 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="profile_picture",
            field=models.ImageField(
                blank=True, null=True, upload_to="profile_pictures/"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("ADMIN", "Administrateur"),
                    ("MANAGER", "Gestionnaire"),
                    ("USER", "Utilisateur"),
                ],
                default="USER",
                max_length=10,
            ),
        ),
    ]
